### ISSUE TITLE
Folder structure very confusing

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-remote-try-java#10]
The folder structure is very confusing especially since the are folders named java. 

![capture](https://user-images.githubusercontent.com/1931590/72060068-8e977400-32d3-11ea-86fb-da750cdbe5cb.png)

**Comment by azusa** [comment]
Hi @dbaeumer  ,
I wonder that folders named `java` is a default folder structure for Java Project with Maven.

**Comment by egamma** [comment]
@azusa is correct this is the folder structure generated by the Maven project generation support. For example:

`mvn archetype:generate -DgroupId=com.test.hello -DartifactId=myproject -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false`

Generates

![image](https://user-images.githubusercontent.com/172399/72336570-50c69100-36c1-11ea-829d-12f83b984427.png)

I haven't found a quick way to not generate the Java folder when using Maven. Therefore I suggest to keep the current folder structure. @Chuxel what do you think?

**Comment by Chuxel** [comment]
@egamma Yes I agree - let's close.
