### ISSUE TITLE
Failed: Copying VS Code server to container

### ISSUE THREAD

**Issue by cqi-ahmedosman** [microsoft/vscode-remote-try-java#2]
Hello, 

Trying to follow the example however it fails in copying VS Code Server from the host to the container. 

Interesting through the server is already there in /tmp/vsch/ but it is failing to be copied for some reason. 

On the host machine, if i try
````
ls /tmp/vsch/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/ 
````
I get

````
vscode-server-linux-x64.tar.gz
````
which means the file exist however i still get an error message saying no such file or directory. 

Below is the error message
````
Installing VS Code Server for commit 57b550c559b945eb9d871dbf2b2e4cb9e31e2551
Run: docker exec 9b62155de4858bc58566dd952692584719e8d205f14d7839f01ca5f4ddd2972a mkdir -p /root/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551_1557584472027
Run: docker cp /tmp/vsch/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/vscode-server-linux-x64.tar.gz 9b62155de4858bc58566dd952692584719e8d205f14d7839f01ca5f4ddd2972a:/root/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551_1557584472027
lstat /tmp/vsch: no such file or directory
Failed: Copying VS Code server to container
Command failed: docker cp /tmp/vsch/57b550c559b945eb9d871dbf2b2e4cb9e31e2551/vscode-server-linux-x64.tar.gz 9b62155de4858bc58566dd952692584719e8d205f14d7839f01ca5f4ddd2972a:/root/.vscode-remote/bin/57b550c559b945eb9d871dbf2b2e4cb9e31e2551_1557584472027
````

**Comment by egamma** [comment]
@cqi-ahmedosman how did you address this problem?

**Comment by cqi-ahmedosman** [comment]
Apologies,  I figured the problem out. The issue is with docker/linux not vscode. 

I had docker installed as a snap which is not supported yet by vscode hence the tmp folder wasn't accessible. When I changed the installation to normal docker installation it worked fine.

**Comment by egamma** [comment]
@cqi-ahmedosman thanks for your explanation, I just wanted to make sure we don't miss anything.
