### ISSUE TITLE
Java home location not found

### ISSUE THREAD

**Issue by andrew-w-ross** [microsoft/vscode-remote-try-java#3]
When trying out the project vscode java extension complains that the java.home folder is not available at `/docker-java-home`.  Changed the location to `/usr/local/openjdk-8` and rebuilt the container and it worked.

**Comment by Chuxel** [comment]
We did not report back, but the base image did in fact change its location, so we added a way to prevent this from happening in the future.  Let us know if you are still seeing an issue.
