### ISSUE TITLE
Added Dockerfile

### ISSUE THREAD

**Issue by f-mohamed-abdullah** [microsoft/vscode-remote-try-java#61]
- Added ```dockerfile```  🐋
- Runned in docker container and i opened pull request <img src="https://img.icons8.com/?size=512&id=TSQGmraGQnmN&format=png" width=20px>
- Please check this 🚀 and merge it <img src="https://img.icons8.com/?size=512&id=C0MLFewYyVBk&format=png" width=20px>
@bamurtaugh , @jdubois , @Chuxel. @egamma

**Comment by bamurtaugh** [comment]
Just cross-posting that I shared our latest thinking in this comment: https://github.com/microsoft/vscode-remote-try-java/pull/60#issuecomment-1647077005.
